# Technically this should be make, should it tho?
debug_build_dir := "build_debug"

compile:
	meson compile -C {{ debug_build_dir }} dire_test

run:
	./{{ debug_build_dir }}/src/test/dire_test

build-and-test-linux: && compile run
	meson setup {{ debug_build_dir }} --buildtype debug --debug -Dbuild_tests=true -Db_lundef=false -Db_sanitize=address,undefined --warnlevel 3

build-and-test-windows: && compile run
	meson setup {{ debug_build_dir }} --buildtype debug --debug -Dbuild_tests=true -Dbackend=vs2022 -Db_sanitize=address --warnlevel 3
