name: 'Generate docs'
on:
  push:
    branches:
      - 'trunk'
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.md'

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated-docs/html
