name: 'Generate docs'
on:
  push:
    branches:
      - 'trunk'
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.md'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout doxygen-awesome
        uses: textbook/git-checkout-submodule-action@master
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated-docs/html
